### ISSUE TITLE
python and ruby version doesn't work

### ISSUE THREAD

**Issue by wx4cb** [KonradIT/GoProStream#4]
require '../gopro-rb-api/lib/GoPro'
require '../gopro-rb-api/lib/constants.rb'

Files do not exist. where can i get . Also, when trying to run the python version, i get urllib errors even though it's installed..

python GoProStream.py
Traceback (most recent call last):
  File "GoProStream.py", line 17, in <module>
    import urllib.request
ImportError: No module named request

root@HP_ENCODER:~/GoProStream# dpkg -l *urllib*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                     Version           Architecture      Description
+++-========================-=================-=================-=====================================================
ii  python-urllib3           1.7.1-1ubuntu4    all               HTTP library with thread-safe connection pooling for
ii  python3-urllib3          1.7.1-1ubuntu4    all               HTTP library with thread-safe connection pooling for

**Comment by KonradIT** [comment]
>python GoProStream.py
Traceback (most recent call last):
File "GoProStream.py", line 17, in
import urllib.request
ImportError: No module named request

You need to run this on Python 3.6, so use virtualenv
